### ISSUE TITLE
When editing an issue the query custom field defaults to the top section and the previous selected option 

### ISSUE THREAD

**Issue by kevins3** [AndreyVMarkelov/mailru-jira-plugins-issue-query-cfs#4]
This means that clicking edit and then save will change the query field option incorrectly as the user has would have to remember to set the field every time an edit is made.

**Comment by kevins3** [comment]
Did you manage to replicate?

**Comment by AndreyVMarkelov** [comment]
Kevin,

No. I don't understand this situation.

-- Andrey M.

Thu, 01 Nov 2012 08:19:20 -0700 от kevins3 notifications@github.com:

> Did you manage to replicate?
> 
> ```
>           —
> 
>           Reply to this email directly or view it on GitHub.
> ```

-- Андрей Маркелов

**Comment by kevins3** [comment]
When adding a JIRA issue you can select an option from the query issue field.
When you view that JIRA issue the correct value is selected.
When you edit the JIRA issue you will see the query issue field has defaulted to the 1st value in the select list , so saving the issue will then incorrectly change the value originally selected.

Let me know if you need more clarity.

**Comment by AndreyVMarkelov** [comment]
Which version of plugin do you use?

**Comment by kevins3** [comment]
Latest. 1.8 I think

Sent from Samsung Mobile

Andrey Markelov notifications@github.com wrote:

Which version of plugin do you use?

—
Reply to this email directly or view it on GitHubhttps://github.com/AndreyVMarkelov/mailru-jira-plugins-issue-query-cfs/issues/4#issuecomment-10010802.

Discovery is an authorised financial services provider.

The information in this email is confidential and may have legal privileges. We intend it only for the use of the individual or entity we've addressed the communication to. If you have received this email by mistake please delete it and tell the sender. We forbid any unauthorised use, change, disclosure or sending of the contents of this email (including its attachments), whether in part or as a whole, unless consented to in writing by the sender, as it may be unlawful.

We cannot guarantee this email has no malicious coding. 

We reserve the right to check, intercept and block emails or take any other action according to our email etiquette. 

Discovery will not be liable for any delivery delay, loss, harm, disruption or data corruption that may arise from this email.

A full list of company directors is available on our website at: https://www.discovery.co.za/info/directors - or to get this list by email, please email directors_list@discovery.co.za

**Comment by AndreyVMarkelov** [comment]
Reproduced. Will be fixed during 2 days.

**Comment by AndreyVMarkelov** [comment]
Done
