### ISSUE TITLE
Enhancement request: I would like the option to select how the list is displayed and select to sort alphabetically on the description field

### ISSUE THREAD

**Issue by kevshine** [AndreyVMarkelov/mailru-jira-plugins-issue-query-cfs#6]

**Comment by AndreyVMarkelov** [comment]
Hi Kevin,

Did you try to use "ORDER BY .. " clause? Forexample, project = AAA and issuetype = Bug ORDER BY description ASC.

Or your request is about other problem?

-- Andrey

**Comment by kevshine** [comment]
LOL. I cant believe I missed that. Yes, that's what I wanted. Thanks.

**Comment by AndreyVMarkelov** [comment]
So, Done:-)
